#!/bin/sh

cfg="${XDG_CONFIG_HOME:-$HOME/.config}/xorg"

[ -d /etc/X11/xinit/xinitrc.d ] && \
	for f in /etc/X11/xinit/xinitrc.d/*; do [ -x "$f" ] && . "$f"; done && unset f

[ -r ~/.wallpaper/default ] && \
	feh --bg-fill --no-fehbg ~/.wallpaper/default || \
	feh --recursive --randomize --bg-fill --no-fehbg ~/.wallpaper

setxkbmap \
	-layout 'us(altgr-intl),de(nodeadkeys)' \
	-option 'grp:shifts_toggle,compose:menu'

xmodmap "$cfg"/us-intl-german.xmodmap

if [ "$(command -v uim-xim >/dev/null >&2)" ]; then
	export GTK_IM_MODULE="uim"
	export QT_IM_MODULE="uim"
	export XMODIFIERS="@im=uim"
fi

# xrdb -merge "$cfg"/Xresources
# xset b off

xinput --set-prop 'Razer Razer Salmosa' 'libinput Accel Speed' -0.7 >/dev/null 2>&1

# color temperature
sct 4400 2>&- || :

exec runsvdir -P ~/service.x 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
