#!/bin/bash

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)
VIM_RC=~/.vimrc

# move vimrc to vimrc.old
if [ -f "$VIM_RC" ]; then
	mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
fi

# link vimrc to repository
ln -sf $BASE/vimrc ~/.vimrc

# install plugins
vim +PlugInstall +qall

