#!/bin/mksh

exec 2>&1

export DISPLAY="${DISPLAY:-:0}"
export XAUTHORITY="${XAUTHORITY:-~/.Xauthority}"

mcookie=$(/usr/bin/mcookie)
xserverauthfile=$(mktemp -p /tmp serverauth.XXXXXXXXXX)

xauth -q -f "$xserverauthfile" add "$DISPLAY" . "$mcookie"
xauth -q add "$DISPLAY" . "$mcookie"

exec xinit "${PWD}/xinit" -- /etc/X11/xinit/xserverrc "$DISPLAY" -noreset -auth "${xserverauthfile}"
