#!/bin/mksh

exec 2>&1

echo "setting up x environment"
xset +fp ~/.fonts/
xset +fp /usr/share/fonts/misc/
xset fp rehash
xset -b

case "$HOSTNAME" in
  tux)
    xrandr --dpi 96
    ;;
  mir02)
    xrandr --dpi 91
    xrandr --output DP1 --left-of DP2
    ;;
esac

setxkbmap de

echo "starting ~/service.x"
exec /usr/bin/ck-launch-session dbus-launch runsvdir ~/service.x
